import test from 'node:test';
import assert from 'node:assert/strict';
import { Game, replay, SEED, FPS, DURATION } from '../src/engine.js';
function play(){const game=new Game(SEED),actions=[];while(!game.finished){if(game.tick%20===0&&game.energy>=20){const targets=game.packets.filter(p=>p.warning===0).sort((a,b)=>Math.hypot(a.x-500,a.y-500)-Math.hypot(b.x-500,b.y-500));if(targets.length){const target=targets[0],to=game.network.map[target.to],length=Math.max(1,Math.hypot(to.x-target.x,to.y-target.y));const a={tick:game.tick,type:'shot',x:target.x+(to.x-target.x)/length*22,y:target.y+(to.y-target.y)/length*22};if(game.act(a))actions.push(a);}}if(game.tick%1100===0){const a={tick:game.tick,type:'scan'};if(game.act(a))actions.push(a);}game.update();}return {game,actions};}
test('client round replay produces identical score, health and timing',()=>{const {game,actions}=play();const result=replay(actions,SEED);assert.equal(result.score,game.score);assert.deepEqual(result.hp,game.hp);assert.equal(result.tick,game.tick);assert.ok(game.intercepted>10);assert.ok(game.score>2000);console.log('Autoplay:',{score:game.score,services:game.services,hits:game.intercepted,duration:game.seconds});});
test('unprotected chain cascades and loses services',()=>{const g=replay([]);assert.equal(g.services,0);assert.ok(g.cascades>0);assert.ok(g.seconds<DURATION);assert.equal(g.score,0);});
test('energy budget, cooldown and regeneration prevent unlimited fields',()=>{const g=new Game();assert.equal(g.act({type:'shot',x:200,y:200}),true);assert.equal(g.energy,80);assert.equal(g.act({type:'shot',x:200,y:200}),false);for(let i=0;i<60;i++)g.update();assert.ok(Math.abs(g.energy-93)<.00001);assert.equal(g.act({type:'shot',x:-1,y:5}),false);assert.equal(g.act({type:'shot',x:NaN,y:5}),false);});
test('scan has a cooldown and slows incoming incidents',()=>{const a=new Game(),b=new Game();for(let i=0;i<155;i++){a.update();b.update();}assert.ok(a.packets.length);assert.equal(a.act({type:'scan'}),true);assert.equal(a.act({type:'scan'}),false);for(let i=0;i<60;i++){a.update();b.update();}assert.ok(a.packets[0].p<b.packets[0].p);});
test('a shield intercepts a packet before it reaches a service',()=>{const g=new Game();const from=g.network.map.i0,to=g.network.map.c0;g.spawn(from.id,to.id,1);g.act({type:'shot',x:from.x,y:from.y});for(let i=0;i<100;i++)g.update();assert.ok(g.intercepted>0);assert.equal(g.hp[0],4);assert.ok(g.score>=100);});
test('replay rejects forged, reordered, excessive or post-round actions',()=>{assert.throws(()=>replay([{tick:0,type:'shot',x:-1,y:5}]));assert.throws(()=>replay([{tick:5,type:'scan'},{tick:1,type:'scan'}]));assert.throws(()=>replay(Array.from({length:1001},()=>({tick:0,type:'scan'}))));assert.throws(()=>replay([{tick:FPS*DURATION,type:'scan'}]));assert.throws(()=>replay([{tick:0,type:'scan'},{tick:1,type:'scan'}]));});
